export const GENDER_OPTIONS = {
  0: "Male",
  1: "Female",
  2: "Transgender",
  3: "Non-binary / Third gender",
  4: "Prefer not to say",
  5: "Other"
}

export const SKILL_OPTIONS = {
  0: "Python",
  1: "Data Science",
  2: "Public Speaking",
  3: "Web Development",
  4: "Photography",
  5: "Guitar",
  6: "Graphic Design",
  7: "Cooking",
  8: "Video Editing",
  9: "Yoga",
  10: "Digital Marketing",
  11: "UI/UX Design",
  12: "Drawing & Sketching",
  13: "Mobile App Development",
  14: "AI & Machine Learning",
  15: "Mathematics Tutoring",
  16: "Creative Writing",
  17: "Blogging & SEO",
  18: "Foreign Languages",
  19: "Chess",
  20: "Meditation",
  21: "Classical Dance",
  22: "Cricket Coaching",
  23: "Spoken English",
  24: "Mandala Art",
  25: "Coding for Kids",
  26: "Music Production",
  27: "Interior Designing",
  28: "Finance & Investing",
  29: "Entrepreneurship",
  30: "Negotiation",
  31: "Innovation",
  32: "Conflict Resolution",
  33: "Project Management",
  34: "Team Leadership",
  35: "Active Listening",
  36: "Emotional Intelligence",
  37: "Critical Thinking",
  38: "Networking",
  39: "Language Translation",
  40: "Podcasting",
  41: "Robotics",
  42: "Singing",
  43: "Baking",
  44: "Gardening",
  45: "Martial Arts",
  46: "Swimming",
  47: "First Aid",
  48: "Carpentry",
  49: "Sewing & Tailoring"
}

export const LANGUAGE_OPTIONS = {
  0: "Assamese",
  1: "Bengali",
  2: "Bodo",
  3: "Dogri",
  4: "Gujarati",
  5: "Hindi",
  6: "Kannada",
  7: "Kashmiri",
  8: "Konkani",
  9: "Maithili",
  10: "Malayalam",
  11: "Manipuri (Meitei)",
  12: "Marathi",
  13: "Nepali",
  14: "Odia",
  15: "Punjabi",
  16: "Sanskrit",
  17: "Santali",
  18: "Sindhi",
  19: "Tamil",
  20: "Telugu",
  21: "Urdu",
  22: "Rajasthani",
  23: "Bhili/Bhilodi",
  24: "Gondi",
  25: "Tulu",
  26: "Kokborok",
  27: "Khasi",
  28: "Mizo",
  29: "Lepcha",
  30: "Ladakhi",
  31: "Garhwali",
  32: "Kumaoni",
  33: "Angika",
  34: "Bhojpuri",
  35: "Magahi",
  36: "Chhattisgarhi",
  37: "Sourashtra",
  38: "Nagpuri",
  39: "Kurukh",
  40: "Ho",
  41: "Mundari",
  42: "Kharia",
  43: "Nicobarese",
  44: "Bhutia",
  45: "Garo",
  46: "Ao",
  47: "Sema",
  48: "Mundari",
  49: "English",
  50: "French",
  51: "Spanish",
  52: "German",
  53: "Arabic",
  54: "Persian",
  55: "Chinese (Mandarin)",
  56: "Japanese",
  57: "Korean",
  58: "Russian",
  59: "Portuguese",
  60: "Italian",
  61: "Other"
}
